### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#13]
I see [in Bolt.pm](https://github.com/majensen/perlbolt/blob/d37bda6dba1565789b20b4f827c3f51eba6a9764/lib/Neo4j/Bolt.pm#L47) that you intentionally disable secure connections using the `NEO4J_INSECURE` flag to `neo4j_connect()`.

Given that Neo4j typically [enables TLS by default](https://neo4j.com/docs/driver-manual/1.7/client-applications/#driver-configuration-encryption) for the Bolt protocol, it may be worth documenting this detail in your readme file until Neo4j::Bolt starts offering secure connections.

**Comment by majensen** [comment]
@johannessen I think this was a workaround for some other issue I was having. I will try to eliminate this.

**Comment by johannessen** [comment]
With the flag gone, I’m now getting -25 errors when trying to connect (`NEO4J_TLS_VERIFICATION_FAILED`).

I’m currently using the self-signed certificate auto-generated by Neo4j 3, so this error is actually to be expected. I think this specific setup would require using [`neo4j_config_set_TLS_ca_file()`](https://neo4j-client.net/doc/latest/neo4j-client_8h.html#a8363cca7d40d34132fb159c84d74d028).

Until we find a better solution, I’ll put the `NEO4J_INSECURE` flag back in and will add the lack of encryption to the documentation.

**Comment by majensen** [comment]
That's interesting, I wasn't seeing that issue on my machine, either local instance or remote.

**Comment by johannessen** [comment]
At first I didn’t see it, either. Maybe libneo4j-client only tries to verify the certificate chain in certain circumstances, but I’m not at all sure what triggers it.

**Comment by majensen** [comment]
I'll try to dig in this wknd

**Comment by johannessen** [comment]
Sounds good.

I just pushed the [feat-encryption](https://github.com/majensen/perlbolt/tree/feat-encryption) branch with https://github.com/majensen/perlbolt/commit/19567cb42e690ef68ae8d6b02638ca0227f08133. This is how far I got the other day. It’s not much, but I guess it’s a start.

Should we delay the CPAN release until TLS works?

**Comment by majensen** [comment]
@johannessen should we call this good? (Yeah, I think TLS should work before we go to CPAN)

**Comment by johannessen** [comment]
So it turns out use of the default trust store is not actually implemented in libneo4j-client.

I’m not sure if the best place to fix that would be in libneo4j-client itself, in Neo4j::Bolt or its client (i. e. Neo4j::Driver).

Fixing it in Perl would require either calling [IO::Socket::SSL::default_ca()](https://metacpan.org/pod/IO::Socket::SSL#IO::Socket::SSL::default_ca(%5B-path%7Cdir%7C-SSL_ca_file-=-...,-SSL_ca_path-=%3E-...-%5D)%3E) or [Mozilla::CA::SSL_ca_file()](https://metacpan.org/pod/Mozilla::CA) and passing the result to `Neo4j::Bolt::connect_()`.

(For the record, it looks like fixing it in libneo4j-client would require calling [SSL_CTX_set_default_verify_paths()](https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html) in [load_certificate_authorities()](https://github.com/cleishm/libneo4j-client/blob/9190be3a92f14208b9debb676dba88c35634eb19/lib/src/openssl.c#L318).)
