### ISSUE TITLE
Release to CPAN

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#14]
To facilitate use of this software, it should be released to CPAN sooner rather than later. I think the following issues should be addressed before that happens:
- ~#4 Unicode support (see PR #10)~
- ~#9 Loading module prints `-lneo4j-client<` to stdout~

- - -

In my opinion, the following issues are somewhat less urgent and could be deferred for future updates. However, addressing these will introduce backwards-incompatible changes in certain edge cases, so it may be advisable to see if there are easy ways to fix them first.
- ~#5 REST::Neo4p as_simple format may conflict with properties~
- ~#11 Paths are returned as array references~
- ~#12  Boolean value representation~
- ~#17 REST::Neo4p as_simple format may conflict with Maps~

- - -

The following issues are IMHO not urgent at all. There should be no need to implement these for the first release:
- ~#6 Obtain the version number of a connected Neo4j server~
- #7 Obtain query execution plans and profiles
- #8 Obtain query notifications
- ~#13 TLS support~
- #19 Empty maps and lists cannot be passed as parameters
- #22 Timeout is not configurable

**Comment by johannessen** [comment]
I’m hoping there currently aren’t any existing clients using Neo4j::Bolt directly. If that’s true, backwards compatibility shouldn’t be an issue.

I intend to offer fixes for #5 and #11 that roughly follow the examples I gave in these two issues. If you'd like me to hold off until we can discuss this, just let me know.

**Comment by johannessen** [comment]
All right, what’s left to do before release?

- Additions to `Build.PL`:
    - `dist_author`
    -     meta_merge => {
            resources => {
              bugtracker => 'https://github.com/majensen/perlbolt/issues',
              repository => 'https://github.com/majensen/perlbolt.git',
            },
          },
    - `no_index => {file => 'Builder.pm'}`, I guess?
- License: Your choice of `apache_2_0` *was* intentional, right?  
  (Just asking because the Perl community tends to prefer either `perl_5` or `artistic_2`. Other than potential future license compatibility issues, I have no problem with the Apache license as such.)
- `Changes` update: either remove entry for 0.1 (= 0.10) or increment module `$VERSION` to match it

Anything else?

**Comment by johannessen** [comment]
All right then!

All that’s left seems to be uploading the distribution to CPAN. I *could* just use my PAUSE id, but you did some amazing work with this project and it really deserves to be published under yours.

<https://github.com/majensen/perlbolt/releases/tag/v0.10>

**Comment by johannessen** [comment]
What do you say, @majensen? Would you like to upload the distribution to CPAN, or should I?

**Comment by majensen** [comment]
I will do it @johannessen very shortly

**Comment by majensen** [comment]
I think I chose Apache 2 in keeping with libneo4j-client... not sure that it matters too much!

**Comment by johannessen** [comment]
Thanks! I didn’t mean to push you. It’s just that I’m eager to release an update of Neo4j::Driver with official Bolt support, and obviously Neo4j::Bolt needs to be released before that can happen.

I just didn’t want to be impolite and publish it *for* you without asking first, that’s all.

**Comment by majensen** [comment]
https://metacpan.org/pod/Neo4j::Bolt !

**Comment by johannessen** [comment]
Great, thanks!

And <https://metacpan.org/pod/Neo4j::Driver> 😎
