### ISSUE TITLE
Push access?

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#15]
Hi Mark, how would you feel about adding me as a GitHub Collaborator for this repo?

There is a chance I might have a little time to work on this project soon. Having push access would make that a little easier.

For starters, I would try to stick to the list of priorities outlined in #14. My motivation is to make this module ready for CPAN release.

In doing so, it would be helpful to know your thinking regarding issues #5, #11, and #12. Ideally, we would discuss these and agree upon a way forward right away. That might also make it easier for me to offer targeted pull requests in case you're not comfortable with me having direct push access.

Cheers,
Arne

**Comment by majensen** [comment]
Hi @johannessen - definitely. Obviously I'm having trouble circling back to it.

**Comment by johannessen** [comment]
Great, thanks! I’m hoping to get on this later this week.
