### ISSUE TITLE
REST::Neo4p as_simple format may conflict with Maps

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#17]
Consider the following two statements:

````
CREATE (n:Universe {answer: 42})
RETURN n AS a
````

````
MATCH  (n:Universe {answer: 42})
CREATE (n)<-[r:FOO]-()
SET    r = { _node: id(n), _labels: ['Universe'], answer: 42 }
RETURN properties(r) AS a
````

The first statement returns a **Node,** the second one a **Map** (of a relationship’s properties).

Two completely different data types with values that have, in principle, nothing at all to do with each other. Yet they both are represented in the exact same way when the corresponding statements are executed with Neo4j::Bolt:

````perl
{
    _node => 306,  # or whichever ID that node has
    _labels => qw(Universe),
    answer => 42,
}
````

Is this a somewhat pathological edge case? Yeah, sure it is.

However, my view is that a module such as Neo4j::Bolt is relatively low-level (or up-river, in CPAN terminology). Such modules should generally try to handle all edge cases correctly.

Therefore, the two statements given above should yield two different results in Perl. It would appear the `as_simple()` format is just not complete enough to do so.

**Comment by majensen** [comment]
@johannessen I grouped the relevant issues into this milestone https://github.com/majensen/perlbolt/milestones/1 - let's get the types right, and then we'll go to CPAN with a first release.
