### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#2]
Eventually we will be needing better error reporting.

For example, at this time, Cypher syntax errors simply cause `Statement evaluation failed` to be written to `stderr`, but no specifics are given, making it difficult for users to debug the issue. Additionally, Neo4j::Bolt does not report the error to its Perl clients; instead, an empty `ResultStream` object is returned, effectively hiding the fact that an error has occurred.

The goal for Neo4j::Bolt might be to `croak` with the original failure code and message as provided by the Neo4j server via Bolt.

**Comment by majensen** [comment]
Getting closer to full error api. Working it out on feat-error-handling branch. Also added travis-ci, which tests a scratch build of libneo4j-client and neo4j community. Passing now in branch, still a few things to do before a merge back to master.

**Comment by majensen** [comment]
With cbebd19d88f353dec01a3090a47118ebfa932794 I'm going to call this done, and wait for more tickets.
