### ISSUE TITLE
How to access result summary and counters?

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#3]
The Neo4j server can provide summary information for statements, such as the count of nodes modified by the statement. How would one access this information using Neo4j::Bolt?

I would need this to implement [Neo4j::Driver::ResultSummary](https://metacpan.org/pod/Neo4j::Driver::ResultSummary) for Bolt. Since it’s not immediately obvious to me how to go about it, I’m asking if you perhaps came across anything connected to the summary in `libneo4j-client`?

**Comment by majensen** [comment]
Probably a way to do it, will work on this next.

**Comment by majensen** [comment]
Provided Neo4j::Bolt::ResultStream with 
update_counts()
result_counts_()
available_after_()
consumed_after_()
at fd42c3c8ed7fcfec2300cdc6205e59c3679f1a4b.

**Comment by johannessen** [comment]
Thanks! That takes care of the counters and timers. I’ve opened #6, #7, #8 about the rest of the result summary information.
