### ISSUE TITLE
Implement spatial and temporal types (Bolt v2)

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#36]
To get [spatial](https://neo4j.com/docs/cypher-manual/4.2/syntax/spatial/) and [temporal](https://neo4j.com/docs/cypher-manual/4.2/syntax/temporal/) Cypher values working in perlbolt, the following needs to be done:

1. **Add support for Bolt v2 types to libneo4j-cypher.**
   The [PackStream](https://7687.org/packstream/packstream-specification-1.html) spec on these types seems simple enough.
   There is already some work on this in the [**neo4j-proto-2**](https://github.com/majensen/libneo4j-client/tree/neo4j-proto-2) branch.
   This topic was also previously discussed in cleishm/libneo4j-client#36 and https://github.com/cleishm/libneo4j-client/issues/49#issuecomment-586677251.
   
2. **Add support for Bolt v2 types to [CTypeHandlers.xs](https://github.com/majensen/perlbolt/blob/master/lib/Neo4j/Bolt/CTypeHandlers.xs).**
   I expect this won’t be too difficult. I might even be able to help – though it may take me a while to get around to it, and at any rate the lib would need to be updated first; see above.

**Comment by johannessen** [comment]
Up to now, I’ve been thinking about how the API for values of these types should look like on the Perl side.

I now have the following proposal for you in the [**bolt-v2-typehandlers**](https://github.com/majensen/perlbolt/tree/bolt-v2-typehandlers) branch:

### Spatial types

Neo4j currently only has two spatial types: 2D point and 3D point. Both are in a proprietary format that requires a custom implementation.

➼ IMHO, the easiest and at the same time the most versatile solution is to use a blessed array ref that uses the exact same format that [PackStream uses in Bolt](https://7687.org/packstream/packstream-specification-1.html#point2d---structure):

````perl
$point = bless [ $neo4j_srid, $x, $y, $z ], 'Neo4j::Bolt::Point'
````

The primary drawback seems to be that the coordinate indeces are 1-based (i. e. `$x = $point->[1]`), whereas in virtually all existing applications they are expected to be 0-based (`$x = $point->[0]`). Given that in Perl this issue can be solved with a simple `shift`, I don’t really worry about that.

````perl
@coordinates = @$point;
$neo4j_srid  = shift @coordinates;
($x, $y, $z) = @coordinates;  # now they are 0-based!
````

A possible alternative that I considered would be to use an extra hash ref to separate SRID and coordinates from each other, but to me, this seems like overkill and a waste of memory.

### Temporal types

Neo4j has a whole bunch of different types for various kinds of dates, times and durations. Pretty standard stuff though.

➼ IMHO, the best solution would probably be to use [DateTime](https://metacpan.org/pod/DateTime) and [DateTime::Duration](https://metacpan.org/pod/DateTime::Duration) here.

Alternatives that I considered:

* [Time::Piece](https://metacpan.org/pod/Time::Piece) looks mighty attractive, because it’s been in Perl core for ages. Unfortunately, it seems to have less precision than Neo4j times have, and [Time::Seconds](https://metacpan.org/pod/Time::Seconds) (which would be used for durations) doesn't handle varying-length spans like “1 month” the same way as Neo4j does.
  
* All Neo4j temporal values can be expressed as strings using the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard. It would be possible to use the Bolt PackStream structure to construct an SV in ISO format, then bless a reference to that. For example:
  ````
  $d = 'PT1M'; $d = bless \$d, 'Neo4j::Bolt::Duration'
  ````
  However, users likely retrieve temporal values from the database because they want to use them for something. Chances are the first thing most users would do is pass such a value to e. g. [DateTime::Format::Duration::ISO8601](https://metacpan.org/pod/DateTime::Format::Duration::ISO8601) to parse the string and yield a DateTime::Duration anyway, making this seem like a bad design choice.

**Comment by majensen** [comment]
@johannessen - finally can work on this with the additions made to libneo4j-client (https://github.com/majensen/libneo4j-client/releases/tag/v5.0.0-maj-beta).

**Comment by majensen** [comment]
@johannessen - please have a look at https://github.com/majensen/perlbolt/tree/v0.5000rc (on feat-v5.0 branch).

**Comment by johannessen** [comment]
Just passing through the temporal struct from Bolt as a hash ref like you do here looks like a reasonable solution to me. While it does place the burden of converting the hash ref to a more practical format on your users, this way you avoid making assumptions on your user’s preferences. That’s fair.

For spatial points, I’d suggest to implement the methods that [Neo4j::Types::Point](https://metacpan.org/pod/Neo4j::Types::Point#METHODS) defines. The default implementation assumes the blessed array structure [suggested above](#issuecomment-758233393), so it’s currently not compatible.
