### ISSUE TITLE
Explain how to obtain the latest release

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#45]
Hey @majensen, I see now that <https://github.com/majensen/perlbolt/releases> claims that the latest release actually is 0.20. The newer versions only show up on GitHub if you click on "show newer tags", which is very easy to miss. I imagine this might have been the reason for the version confusion in https://github.com/majensen/perlbolt/issues/43.

I’m not really sure what the best solution would be here, but IMHO one part of it is that the readme at <https://github.com/majensen/perlbolt> should describe one way (and only one way) for getting the latest release. For example, either a link to MetaCPAN or a pointer to the GitHub releases (not both). When there are multiple sources, I think it’s just too easy to forget updating one of them.

What do you think?

**Comment by majensen** [comment]
Thanks @johannessen - I agree and vote for github. I'm may have some time this week to devote to this, off $job.

**Comment by johannessen** [comment]
Aside from the pointer in the readme, I’ve also added a GitHub release similar to your earlier ones back from 2020. I hope this is okay with you! Obviously, feel free to etc. etc.

https://github.com/majensen/perlbolt/releases/tag/v0.4203

Come to think of it now, the pointer in the release may even be clear enough so the readme note isn’t needed at all…

**Comment by johannessen** [comment]
I suppose the link to CPAN in the GH "release" tag addresses this sufficiently. Closing.
