### ISSUE TITLE
Does Neo4j-Bolt v0.4201 work with neo4j 4.2.x?

### ISSUE THREAD

**Issue by foobargeez** [majensen/perlbolt#48]
Hi,
Lost track of what exactly is needed to make Neo4j::Bolt talk to Neo4j v4.2.x or higher.  I recall libneo4j-client is patched but not merged pending review but not sure if the patched library is installed as part of Neo4j:Bolt v0.4201 or a separate installation is needed etc., 

Would really appreciate any pointers .. 

Thanks!

**Comment by johannessen** [comment]
Yep, works fine with 4.2 + 4.3! Just make sure you install the latest versions from CPAN. The patched lib will be included.
https://metacpan.org/pod/Neo4j::Client
https://metacpan.org/pod/Neo4j::Bolt
https://metacpan.org/pod/Neo4j::Driver

(Not sure if anyone has gotten around to test with 4.4 yet.)

**Comment by foobargeez** [comment]
Thanks!

I am on Neo4j::Bolt v0.4201 and Neo4j::Client v0.46 and when trying to connect, getting `Bad Request (connect phase 2)` .. 

Environment:
Cent OS and Perl v5.26.1

Not sure if I am missing anything else ..

**Comment by johannessen** [comment]
Hm, that message doesn’t sound like it comes from Neo4j::Bolt.

Could you show the code snippet that produces the error?

**Comment by foobargeez** [comment]
You're right .. my code uses both REST::Neo4p (legacy code) and Neo4j::Bolt.  Just commented out REST::Neo4p connection part and I am able to connect to Neo4j v4.2.x.

Took some time to figure out how to specify the DB to connect to and looking at the tests, I need to set `$Neo4j::Bolt::DEFAULT_DB`.

Just wondering - does REST::Neo4p work with Neo4j 4.x via HTTP or do I have to migrate that code to a separate module.  I will dig the release notes and/or source code but if you know on top of your head, I will appreciate it.

Thanks again!

**Comment by foobargeez** [comment]
Alright, I installed `REST::Neo4p::Agent::Neo4j::Driver` and set `$REST::Neo4p::AGENT_MODULE` to `Neo4j::Driver` and I am all set.

Thanks!

**Comment by johannessen** [comment]
> Just commented out REST::Neo4p connection part and I am able to connect to Neo4j v4.2.x.

Good to hear!


> Took some time to figure out how to specify the DB to connect to and looking at the tests, I need to set `$Neo4j::Bolt::DEFAULT_DB`.

FWIW, the driver uses an undocumented parameter in `run_query()`.
https://metacpan.org/release/AJNN/Neo4j-Driver-0.27/source/lib/Neo4j/Driver/Net/Bolt.pm#L123


> Just wondering - does REST::Neo4p work with Neo4j 4.x via HTTP or do I have to migrate that code to a separate module.

@majensen wrote a compatibility layer for REST::Neo4p using Neo4j::Driver, so that should work, too.

**Comment by foobargeez** [comment]
I am still going a bit crazy to figure out how to pass database name (I use non-system database) from REST::Neo4p to Neo4j::Driver .. any ideas?

**Comment by johannessen** [comment]
I’m no longer familiar enough with Neo4p to give a good answer to that … but try something like this:

````perl
REST::Neo4p->agent->database( $name );
````

If that doesn’t help, I’d say it’d be best to open a new issue over at [majensen/rest-neo4p](https://github.com/majensen/rest-neo4p).

**Comment by johannessen** [comment]
BTW, I don’t think this is documented anywhere, but thanks to Neo4j::Driver and Neo4j::Bolt, you should also be able to connect Neo4p using a `bolt:` URL. In fact, this is the setup that I’d recommend for best performance, given how chatty Neo4p is.
