### ISSUE TITLE
Bolt v5 support

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#54]
Re https://github.com/majensen/perlbolt/issues/50#issuecomment-1512424819:

> Have a try of https://github.com/majensen/perlbolt/tree/v0.5000rc (in feat-v5.0) for element ids in Nodes and Relationships.

I finally looked into this today. Sorry it took so long.

However, I can’t get the feat-v5.0 branch to connect properly using Bolt v5.

```sh
git checkout v0.5000rc
perl Makefile.PL
make
perl -Iblib/arch -Iblib/lib -MNeo4j::Bolt -E "say Neo4j::Bolt->connect(...)->protocol_version"
```

Tried with Neo4j 5.1, 5.3, 5.6; these always yield a Bolt version 4.0 connection. Then tried with Neo4j 5.9, got a segfault ([libneo4j-omni#3](https://github.com/majensen/libneo4j-omni/issues/3)). Then tried Neo4j 5.8, for which perlbolt claims to get a Bolt version 5.0 connection – except that [Bolt 5.0 isn’t declared as supported by the client](https://github.com/majensen/libneo4j-client/blob/346ad1abef213161a29f2cb7b43331bb66d913c9/lib/src/connection.c#L426-L432), so I don’t see how that is even possible.

With that so-called “Bolt 5.0” connection to Neo4j 5.8, `make test` fails.

Trying to run any query manually fails as well, with a “… session in the AUTHENTICATION state” message. (Yes, the credentials are correct.)

```
$ perl -Iblib/arch -Iblib/lib -MNeo4j::Bolt -E "Neo4j::Bolt->set_log_level('TRACE'); Neo4j::Bolt->connect(...)->run_query('RETURN 1')"
...
TRACE [results]: FAILURE in 0x7f9a6855b940 (response to RUN): {code:"Neo.ClientError.Request.Invalid",message:"Message 'RunMessage{bookmarks=[], txTimeout=null, accessMode=WRITE, txMetadata=null, databaseName='neo4j', impersonatedUser='null', notificationsConfig=Default, statement='RETURN 1', params=Map{}}' cannot be handled by a session in the AUTHENTICATION state."}
```

I have Neo4j::Client 0.52, which is the latest version. Trying 0.51 or 0.50 didn’t seem to change anything.

Am I missing something obvious here?

**Comment by majensen** [comment]
Hey Arne- yes, there is def an issue with the version selection in libneo. I've noticed it myself using the cli client. Maybe I can look into it during the next couple of days (holidays here). In the meantime it's reasonable to limit to >=4.

**Comment by johannessen** [comment]
Right, I forgot. Happy Thanksgiving! 🙂

**Comment by johannessen** [comment]
@majensen Hey Mark, I'm working on an update to Neo4j::Driver that would benefit from Bolt v5 support being available on CPAN. It seems that the effort to release Perl support for Bolt v5 is currently stalled.

Fixes for the minor issues that had been blocking a working release are in https://github.com/majensen/perlbolt/pull/59 and in https://github.com/majensen/libneo4j-omni/pull/9.

Additionally, the submodule in the neoclient repository will need to be updated after the libneo4j-omni fix has been applied. https://github.com/majensen/neoclient/pull/4 doesn't yet include it.

What else can I do to help?

**Comment by majensen** [comment]
Hey @johannessen - it's obviously been really tough for me to get back over to this. I'll have to give it a weekend at least, so it will prob be May before I can look at it.

**Comment by johannessen** [comment]
Apparently it’s [CPAN Day](https://blogs.perl.org/users/neilb/2014/08/cpan-day---start-your-engines.html). Any progress on getting this released? 🙂

**Comment by johannessen** [comment]
Hey Mark, it seems that this effort has stalled, even though all the work is already complete.

Could you please tell me where we are vis-à-vis the CPAN release?
